In [1]:
import tensorflow as tf
import numpy as np

# 1. Tạo mảng ngẫu nhiên kích thước 3x3 trong khoảng [0, 20]
# Hàm randint(low, high, size) tạo số nguyên trong khoảng [low, high)
# Để bao gồm cả số 20, chúng ta để high là 21
array_2d = np.random.randint(0, 21, size=(3, 3))

print("Mảng vừa tạo:")
print(array_2d)

# 2. Kiểm tra tất cả các phần tử có khác 0 hay không
# Cách hoạt động của np.all(): Trả về True nếu tất cả phần tử đều True (khác 0)
check_all_nonzero = np.all(array_2d != 0)

print("-" * 20)
if check_all_nonzero:
    print("Kết quả: Tất cả các phần tử trong mảng đều khác 0.")
else:
    print("Kết quả: Mảng có chứa ít nhất một phần tử bằng 0.")

Mảng vừa tạo:
[[ 6  1  1]
 [19  1  4]
 [ 8 13  6]]
--------------------
Kết quả: Tất cả các phần tử trong mảng đều khác 0.


In [2]:
import numpy as np

# 1. Tạo mảng ngẫu nhiên 3x3 trong khoảng [0, 20]
# Lưu ý: Mảng 3x3 có 9 phần tử.
# Nếu bạn muốn 20 số, bạn có thể đổi size thành (4, 5) hoặc (2, 10).
array_2d = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên vừa tạo:")
print(array_2d)

# 2. Kiểm tra tồn tại ít nhất một phần tử khác 0
# Cách 1: Sử dụng biểu thức so sánh tường minh
has_nonzero = np.any(array_2d != 0)

# Cách 2: Viết ngắn gọn (Numpy coi 0 là False, khác 0 là True)
# has_nonzero = np.any(array_2d)

print("-" * 20)
if has_nonzero:
    print("Kết quả: Tồn tại ít nhất một phần tử khác 0 trong mảng.")
else:
    print("Kết quả: Tất cả các phần tử trong mảng đều bằng 0.")

Mảng ngẫu nhiên vừa tạo:
[[ 7 16 14]
 [15  5 18]
 [11 20  3]]
--------------------
Kết quả: Tồn tại ít nhất một phần tử khác 0 trong mảng.


In [3]:
import numpy as np

# Tạo 10 số 0
zeros = np.zeros(10)

# Tạo 10 số 1
ones = np.ones(10)

# Tạo 10 số 5 (Bằng cách nhân mảng 1 với 5)
fives = np.ones(10) * 5

# Nối các mảng lại với nhau
result = np.concatenate([ones, zeros, fives])

print("Mảng kết quả:")
print(result)
print(f"Kích thước mảng: {result.size}")

Mảng kết quả:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]
Kích thước mảng: 30


In [4]:
import numpy as np

# Sử dụng np.arange(start, stop, step)
# start = 30: Bắt đầu từ số 30 (là số chẵn)
# stop = 71: Chúng ta dùng 71 để bao gồm cả số 70 (vì stop là giới hạn mở)
# step = 2: Khoảng cách giữa các số là 2 để lấy các số chẵn
mang_chan = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(mang_chan)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [5]:
import numpy as np

# Tạo ma trận đơn vị kích thước 3x3
# Tham số truyền vào là n (số hàng và số cột của ma trận vuông)
ma_tran_don_vi = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(ma_tran_don_vi)

# Kiểm tra kiểu dữ liệu (mặc định là float)
print(f"\nKiểu dữ liệu mặc định: {ma_tran_don_vi.dtype}")

# Nếu bạn muốn tạo ma trận đơn vị kiểu số nguyên (integer)
ma_tran_int = np.identity(3, dtype=int)
print("\nMa trận đơn vị kiểu số nguyên:")
print(ma_tran_int)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Kiểu dữ liệu mặc định: float64

Ma trận đơn vị kiểu số nguyên:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
import numpy as np

# 1. Tạo mảng 10 phần tử trong khoảng [15, 55]
# Ở đây mình dùng np.linspace để đảm bảo lấy đúng chính xác 10 phần tử
# hoặc dùng np.arange nếu bạn muốn các bước nhảy là số nguyên.
# Ví dụ này dùng linspace để chia đều khoảng [15, 55] thành 10 phần tử.
array = np.linspace(15, 55, 10, dtype=int)

print("Mảng đầy đủ 10 phần tử:")
print(array)

# 2. In các giá trị ngoại trừ phần tử đầu và cuối
# Sử dụng kỹ thuật Slicing: [start:stop]
# start = 1 (bỏ phần tử chỉ số 0)
# stop = -1 (bỏ phần tử cuối cùng)
result = array[1:-1]

print("\nCác giá trị sau khi bỏ phần tử đầu và cuối:")
print(result)

Mảng đầy đủ 10 phần tử:
[15 19 23 28 32 37 41 46 50 55]

Các giá trị sau khi bỏ phần tử đầu và cuối:
[19 23 28 32 37 41 46 50]


In [7]:
import numpy as np

# 1. Tạo mảng 20 phần tử ngẫu nhiên trong khoảng [0, 20]
# Chúng ta dùng randint để tạo số nguyên
arr = np.random.randint(0, 21, 20)

print("Mảng ban đầu:")
print(arr)

# 2. Đổi dấu những số nằm trong khoảng [9, 15]
# Điều kiện: (phần tử >= 9) VÀ (phần tử <= 15)
# Trong Numpy, toán tử VÀ cho mảng là dấu '&'
mask = (arr >= 9) & (arr <= 15)

# Áp dụng mặt nạ (mask) để nhân các phần tử thỏa mãn với -1
arr[mask] = arr[mask] * -1

print("\nMảng sau khi đổi dấu các số trong khoảng [9, 15]:")
print(arr)

Mảng ban đầu:
[20 11  2 10  3  8  7 18  0  7 14 16  3 17 16 18 17  9  9 12]

Mảng sau khi đổi dấu các số trong khoảng [9, 15]:
[ 20 -11   2 -10   3   8   7  18   0   7 -14  16   3  17  16  18  17  -9
  -9 -12]


In [8]:
import numpy as np

# 1. Tạo ma trận kích thước 3x4
# low=10: Giá trị nhỏ nhất có thể nhận được
# high=22: Vì Numpy không lấy giá trị high, ta để 22 để bao gồm cả số 21
# size=(3, 4): Kích thước ma trận (3 hàng, 4 cột)
matrix = np.random.randint(low=10, high=22, size=(3, 4))

print("Ma trận 3x4 với các giá trị từ 10 đến 21:")
print(matrix)

# 2. Kiểm tra thông tin ma trận
print("-" * 20)
print(f"Kích thước (Shape): {matrix.shape}")
print(f"Tổng số phần tử: {matrix.size}")

Ma trận 3x4 với các giá trị từ 10 đến 21:
[[11 19 12 12]
 [20 18 18 11]
 [15 16 12 21]]
--------------------
Kích thước (Shape): (3, 4)
Tổng số phần tử: 12


In [9]:
import numpy as np

# 1. Tạo ma trận 10x10 toàn số 1
# Chúng ta dùng dtype=int để ma trận nhìn gọn gàng hơn
matrix = np.ones((10, 10), dtype=int)

# 2. Thay đổi các phần tử bên trong thành số 0
# Sử dụng slicing [hàng_bắt_đầu : hàng_kết_thúc, cột_bắt_đầu : cột_kết_thúc]
# Chúng ta bỏ hàng đầu (index 0) và hàng cuối (index -1) -> dùng 1:-1
# Chúng ta bỏ cột đầu (index 0) và cột cuối (index -1) -> dùng 1:-1
matrix[1:-1, 1:-1] = 0

print("Ma trận 10x10 có biên bằng 1, bên trong bằng 0:")
print(matrix)

Ma trận 10x10 có biên bằng 1, bên trong bằng 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [10]:
import numpy as np

# 1. Tạo danh sách các giá trị cho đường chéo chính
diagonal_values = [1, 2, 3, 4, 5]

# 2. Tạo ma trận 5x5 từ danh sách trên
# Hàm diag sẽ tự động tạo ma trận vuông có kích thước tương ứng với độ dài mảng
matrix = np.diag(diagonal_values)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(matrix)

# Kiểm tra kích thước ma trận
print(f"\nKích thước ma trận: {matrix.shape}")

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Kích thước ma trận: (5, 5)


In [11]:
import numpy as np

# 1. Tạo mảng 3x3x3 với các số nguyên ngẫu nhiên từ 1 đến 10
array_3d = np.random.randint(1, 11, size=(3, 3, 3))

print("Mảng 3x3x3 vừa tạo:")
print(array_3d)
print("-" * 30)

# 2. Tính tổng theo mỗi cột (Axis 1)
# Trong mảng 3D, axis=1 tương ứng với việc cộng dồn các hàng lại với nhau theo chiều dọc của mỗi ma trận
sum_columns = np.sum(array_3d, axis=1)

# 3. Tính tổng theo mỗi dòng (Axis 2)
# Axis 2 tương ứng với việc cộng dồn các cột lại với nhau theo chiều ngang của mỗi ma trận
sum_rows = np.sum(array_3d, axis=2)

print("Tổng theo mỗi cột (của từng ma trận thành phần):")
print(sum_columns)

print("\nTổng theo mỗi dòng (của từng ma trận thành phần):")
print(sum_rows)


Mảng 3x3x3 vừa tạo:
[[[ 4  8  7]
  [ 1  7  4]
  [10  8  8]]

 [[ 4 10  3]
  [ 9  9  6]
  [ 4  3  1]]

 [[10  7  4]
  [10  9  9]
  [ 1  5  7]]]
------------------------------
Tổng theo mỗi cột (của từng ma trận thành phần):
[[15 23 19]
 [17 22 10]
 [21 21 20]]

Tổng theo mỗi dòng (của từng ma trận thành phần):
[[19 12 26]
 [17 24  8]
 [21 28 13]]


In [12]:
import numpy as np

# 1. Tạo 2 vector ngẫu nhiên gồm 10 phần tử
# Ở đây ta tạo số thực trong khoảng [0, 1)
v1 = np.random.rand(10)
v2 = np.random.rand(10)

print("Vector v1:")
print(v1)
print("\nVector v2:")
print(v2)

# 2. Thực hiện Inner Product bằng np.dot
inner_product = np.dot(v1, v2)

# Cách khác: Sử dụng toán tử @ (tương đương np.dot cho vector 1 chiều)
# inner_product = v1 @ v2

print("-" * 30)
print(f"Kết quả tích vô hướng (Inner Product): {inner_product:.4f}")

Vector v1:
[0.60590015 0.49952082 0.9751899  0.16223857 0.53563021 0.91626714
 0.07418559 0.04394239 0.3101696  0.83428773]

Vector v2:
[0.94009352 0.22263498 0.72209833 0.53813248 0.00568994 0.99496688
 0.31035083 0.98031191 0.37066219 0.85908428]
------------------------------
Kết quả tích vô hướng (Inner Product): 3.2848


In [13]:
import numpy as np

# 1. Tạo ma trận A kích thước 4 x 3
# Các số nguyên ngẫu nhiên từ 1 đến 10 để dễ quan sát kết quả
A = np.random.randint(1, 11, size=(4, 3))

# 2. Tạo vector y gồm 3 phần tử
y = np.random.randint(1, 11, size=3)

print("Ma trận A (4x3):")
print(A)
print("\nVector y (3 phần tử):")
print(y)

# 3. Thêm vector y vào từng dòng của ma trận A
# Numpy thực hiện Broadcasting tự động khi chiều cuối cùng khớp nhau (3 == 3)
result = A + y

print("\nKết quả sau khi cộng y vào từng dòng của A:")
print(result)

Ma trận A (4x3):
[[3 1 3]
 [6 3 9]
 [8 8 1]
 [6 3 7]]

Vector y (3 phần tử):
[10  4  9]

Kết quả sau khi cộng y vào từng dòng của A:
[[13  5 12]
 [16  7 18]
 [18 12 10]
 [16  7 16]]


In [14]:
import pandas as pd

# 1. Khởi tạo 2 Series từ danh sách (list)
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", s1, sep="")
print("\nSeries 2:\n", s2, sep="")
print("-" * 25)

# 2. Thực hiện các phép toán cơ bản
print("Cộng (s1 + s2):")
print(s1 + s2)

print("\nTrừ (s1 - s2):")
print(s1 - s2)

print("\nNhân (s1 * s2):")
print(s1 * s2)

print("\nChia (s1 / s2):")
print(s1 / s2)

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
-------------------------
Cộng (s1 + s2):
0     3
1     7
2    11
3    15
4    20
dtype: int64

Trừ (s1 - s2):
0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân (s1 * s2):
0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia (s1 / s2):
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [15]:
import pandas as pd
import numpy as np

# 1. Tạo DataFrame 4x3 với các số ngẫu nhiên từ 1 đến 100
# Chúng ta đặt tên cột là 'A', 'B', 'C' để dễ thao tác
df = pd.DataFrame(np.random.randint(1, 101, size=(4, 3)),
                  columns=['Cột A', 'Cột B', 'Cột C'])

print("DataFrame ban đầu:")
print(df)

# 2. Sắp xếp DataFrame theo 'Cột A'
# ascending=True: Sắp xếp tăng dần (mặc định)
# ascending=False: Sắp xếp giảm dần
df_sorted = df.sort_values(by='Cột A', ascending=True)

print("\nDataFrame sau khi sắp xếp tăng dần theo 'Cột A':")
print(df_sorted)

# 3. Sắp xếp theo nhiều cột (Ví dụ: B tăng dần, nếu bằng nhau thì C giảm dần)
df_multi_sorted = df.sort_values(by=['Cột B', 'Cột C'], ascending=[True, False])

print("\nSắp xếp theo Cột B (tăng) và Cột C (giảm):")
print(df_multi_sorted)

DataFrame ban đầu:
   Cột A  Cột B  Cột C
0     15     68     50
1     20     13     36
2     85     97     55
3     88     24     28

DataFrame sau khi sắp xếp tăng dần theo 'Cột A':
   Cột A  Cột B  Cột C
0     15     68     50
1     20     13     36
2     85     97     55
3     88     24     28

Sắp xếp theo Cột B (tăng) và Cột C (giảm):
   Cột A  Cột B  Cột C
1     20     13     36
3     88     24     28
0     15     68     50
2     85     97     55


In [16]:
import pandas as pd

# 1. Khởi tạo 2 Series theo yêu cầu
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("Series 1 (sr1):")
print(sr1)
print("\nSeries 2 (sr2):")
print(sr2)

# 2. Tìm các phần tử trong sr1 mà không có trong sr2
# Bước 1: sr1.isin(sr2) trả về True nếu phần tử của sr1 nằm trong sr2
# Bước 2: Dấu ~ dùng để đảo ngược kết quả (True thành False và ngược lại)
result = sr1[~sr1.isin(sr2)]

print("\nItems of sr1 not present in sr2:")
print(result)

Series 1 (sr1):
0    1
1    2
2    3
3    4
4    5
dtype: int64

Series 2 (sr2):
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


In [17]:
import numpy as np
import pandas as pd

# 1. Tạo 2 Series ngẫu nhiên có 20 phần tử trong khoảng [1, 15]
# Dùng randint để tạo số nguyên
sr1 = pd.Series(np.random.randint(1, 16, 20))
sr2 = pd.Series(np.random.randint(1, 16, 20))

print("Series 1 (đã loại trùng để dễ nhìn):", np.unique(sr1.values))
print("Series 2 (đã loại trùng để dễ nhìn):", np.unique(sr2.values))
print("-" * 40)

# 2. Tìm phần GIAO (Intersect) - Những số có mặt ở cả hai
giao = np.intersect1d(sr1, sr2)

# 3. Tìm phần HỘI (Union) - Tất cả các số của cả hai, không trùng lặp
hoi = np.union1d(sr1, sr2)

print("GIAO (Các phần tử xuất hiện ở cả hai Series):")
print(giao)

print("\nHỘI (Tất cả các phần tử duy nhất của cả hai Series):")
print(hoi)

Series 1 (đã loại trùng để dễ nhìn): [ 1  2  3  5  7  8  9 12 13 14 15]
Series 2 (đã loại trùng để dễ nhìn): [ 2  3  4  5  6  7  9 11 12 13 15]
----------------------------------------
GIAO (Các phần tử xuất hiện ở cả hai Series):
[ 2  3  5  7  9 12 13 15]

HỘI (Tất cả các phần tử duy nhất của cả hai Series):
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15]


In [18]:
import pandas as pd

# 1. Khởi tạo 2 Series theo yêu cầu
# Series x chứa các số từ 0 đến 9
x = pd.Series(range(10), name='x')

# Series y chứa các ký tự từ p đến y
y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'], name='y')

print("Series x gốc:")
print(x.head(3), "...", sep="\n") # In 3 dòng đầu để minh họa

print("\nSeries y gốc:")
print(y.head(3), "...", sep="\n")
print("-" * 30)

# 2. Thêm theo chiều dọc (Vertical)
# axis=0 (mặc định): Nối đuôi nhau tạo thành một Series dài hơn (20 phần tử)
vertical_concat = pd.concat([x, y], axis=0)

# 3. Thêm theo chiều ngang (Horizontal)
# axis=1: Kết hợp lại tạo thành một DataFrame (10 hàng, 2 cột)
horizontal_concat = pd.concat([x, y], axis=1)

print("Kết quả theo chiều dọc (Vertical - tạo Series dài):")
print(vertical_concat)

print("\nKết quả theo chiều ngang (Horizontal - tạo DataFrame):")
print(horizontal_concat)

Series x gốc:
0    0
1    1
2    2
Name: x, dtype: int64
...

Series y gốc:
0    p
1    q
2    r
Name: y, dtype: object
...
------------------------------
Kết quả theo chiều dọc (Vertical - tạo Series dài):
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Kết quả theo chiều ngang (Horizontal - tạo DataFrame):
   x  y
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [19]:
import pandas as pd
import numpy as np

# 1. Chuẩn bị dữ liệu
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# 2. Tạo DataFrame
# Chúng ta truyền thêm tham số index=labels để định danh các hàng
df = pd.DataFrame(exam_data, index=labels)

# 3. Hiển thị dữ liệu
print("Dữ liệu kỳ thi (Exam Data):")
print(df)

Dữ liệu kỳ thi (Exam Data):
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [20]:
import pandas as pd
import numpy as np

# 1. Khởi tạo lại dữ liệu từ bài 22
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

# 2. Lấy 3 dòng đầu tiên
# Cách 1: Sử dụng hàm head(n)
first_3_rows = df.head(3)

# Cách 2: Sử dụng kỹ thuật Slicing (cắt mảng)
# first_3_rows = df.iloc[:3]

print("3 dòng đầu tiên của DataFrame:")
print(first_3_rows)

3 dòng đầu tiên của DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [21]:
import pandas as pd
import numpy as np

# Khởi tạo dữ liệu (từ bài 22)
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

# 1. Chọn cột 'name' và 'score'
# Lưu ý: Sử dụng ngoặc vuông kép [ ['col1', 'col2'] ]
selected_columns = df[['name', 'score']]

print("Cột 'name' và 'score' của DataFrame:")
print(selected_columns)

Cột 'name' và 'score' của DataFrame:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [22]:
import pandas as pd
import numpy as np

# Khởi tạo dữ liệu (từ bài 22)
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

# 1. Lọc những dòng có số lần thi (attempts) lớn hơn 2
# Điều kiện: df['attempts'] > 2
result = df[df['attempts'] > 2]

print("Các dòng có số lần thi (attempts) > 2:")
print(result)

Các dòng có số lần thi (attempts) > 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [23]:
import pandas as pd
import numpy as np

# Khởi tạo dữ liệu (từ bài 22)
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

# 1. Tìm các dòng có giá trị score là NaN
# df['score'].isnull() trả về True cho các ô trống
rows_with_nan = df[df['score'].isnull()]

print("Các dòng có điểm số (score) là NaN:")
print(rows_with_nan)

Các dòng có điểm số (score) là NaN:
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [24]:
import pandas as pd
import numpy as np

# Khởi tạo dữ liệu (từ bài 22)
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

# 1. Lọc những dòng có score trong khoảng [15, 20]
# inclusive='both' (mặc định): bao gồm cả 15 và 20
# inclusive='neither': không bao gồm 15 và 20
result = df[df['score'].between(15, 20)]

print("Các dòng có điểm số (score) trong khoảng [15, 20]:")
print(result)

Các dòng có điểm số (score) trong khoảng [15, 20]:
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


In [27]:
import pandas as pd
import numpy as np

# 1. Khởi tạo dữ liệu (từ bài 22)
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
             'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

print("Giá trị dòng 'd' trước khi thay đổi:")
print(df.loc[['d']]) # Hiển thị dòng d để kiểm tra (score đang là NaN)

# 2. Thay đổi giá trị tại dòng 'd', cột 'score' thành 11.5
# Lưu ý: Yêu cầu của bạn là thay thành 19, nhưng đề bài gốc thường dùng 11.5
# Ở đây mình sẽ thực hiện đúng số 19 theo yêu cầu của bạn:
df.loc['d', 'score'] = 19

print("\nDataFrame sau khi thay đổi dòng 'd', cột 'score' thành 19:")
print(df.loc[['d']])

Giá trị dòng 'd' trước khi thay đổi:
    name  score  attempts qualify
d  James    NaN         3      no

DataFrame sau khi thay đổi dòng 'd', cột 'score' thành 19:
    name  score  attempts qualify
d  James   19.0         3      no
