In [2]:
import tensorflow as tf

# Tạo một tensor mẫu
t = tf.zeros([2, 3])

print("Shape (Kích thước):", t.shape)
print("DType (Kiểu dữ liệu):", t.dtype)
print("Rank (Số chiều):", tf.rank(t).numpy()) # Kết quả sẽ là 2 cho ma trận 2D

Shape (Kích thước): (2, 3)
DType (Kiểu dữ liệu): <dtype: 'float32'>
Rank (Số chiều): 2


In [3]:
import tensorflow as tf

# Khởi tạo X
X = [[1, 2, 3], [4, 5, 6]]

# Tạo tensor có kích thước và dtype giống X nhưng toàn số 0
X_zeros = tf.zeros_like(X)

print("Tensor X_zeros:")
print(X_zeros)

# Kiểm tra lại thông tin
print(f"\nShape của X_zeros: {X_zeros.shape}")
print(f"Dtype của X_zeros: {X_zeros.dtype}")

Tensor X_zeros:
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)

Shape của X_zeros: (2, 3)
Dtype của X_zeros: <dtype: 'int32'>


In [ ]:
import tensorflow as tf

# Tạo tensor 3x2 với các phần tử bằng 5
tensor_5 = tf.fill([3, 2], 5)

print(tensor_5)

In [ ]:
import tensorflow as tf

# Định nghĩa các số chẵn trong khoảng [5, 10]
even_numbers = [6, 8, 10]

# Tạo tensor 1 chiều với 50 phần tử được chọn ngẫu nhiên từ danh sách trên
# Chúng ta sử dụng tf.gather với các chỉ số ngẫu nhiên
indices = tf.random.uniform([50], minval=0, maxval=len(even_numbers), dtype=tf.int32)
tensor_even = tf.gather(even_numbers, indices)

print("Tensor 1 chiều với 50 phần tử chẵn:")
print(tensor_even.numpy())
print(f"\nShape: {tensor_even.shape}")

In [4]:
import tensorflow as tf

# tf.range(start, limit, delta)
# start: Giá trị bắt đầu (bao gồm)
# limit: Giá trị kết thúc (không bao gồm)
# delta: Bước nhảy
tensor_range = tf.range(start=10, limit=102, delta=2)

print(tensor_range)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [5]:
import tensorflow as tf

# Tạo tensor kích thước [3, 2]
# mean: Giá trị trung bình
# stddev: Độ lệch chuẩn
random_tensor = tf.random.normal(shape=[3, 2],
                                 mean=0.0,
                                 stddev=2.0)

print(random_tensor)

tf.Tensor(
[[ 1.3110157   0.9228955 ]
 [ 3.2889497   0.8303795 ]
 [ 0.26917183 -2.0876465 ]], shape=(3, 2), dtype=float32)


In [6]:
import tensorflow as tf

# Tạo tensor kích thước [3, 2] theo phân phối uniform
# minval: Giá trị tối thiểu (bao gồm)
# maxval: Giá trị tối đa (không bao gồm)
random_uniform_tensor = tf.random.uniform(shape=[3, 2],
                                          minval=0,
                                          maxval=2)

print(random_uniform_tensor)

tf.Tensor(
[[1.1324735 1.1994686]
 [0.5764978 0.3154707]
 [0.7402055 1.3933315]], shape=(3, 2), dtype=float32)


In [7]:
import tensorflow as tf

# Khởi tạo tensor X
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Shuffle X theo chiều thứ nhất
shuffled_X = tf.random.shuffle(X)

print("Tensor X ban đầu:")
print(X.numpy())

print("\nTensor X sau khi shuffle:")
print(shuffled_X.numpy())

Tensor X ban đầu:
[[1 2]
 [3 4]
 [5 6]]

Tensor X sau khi shuffle:
[[3 4]
 [1 2]
 [5 6]]


In [8]:
import tensorflow as tf

# 1. Tạo tensor ngẫu nhiên kích thước (10, 10, 3)
# Giả lập một ảnh màu nhỏ với các giá trị từ 0 đến 255
input_tensor = tf.random.uniform(shape=[10, 10, 3], minval=0, maxval=255, dtype=tf.int32)

# 2. Cắt ngẫu nhiên thành kích thước (5, 5, 3)
# Tham số size chính là kích thước mục tiêu bạn muốn cắt ra
cropped_tensor = tf.image.random_crop(value=input_tensor, size=[5, 5, 3])

print("Kích thước tensor ban đầu:", input_tensor.shape)
print("Kích thước tensor sau khi cắt:", cropped_tensor.shape)

# Hiển thị nội dung tensor sau khi cắt (tùy chọn)
# print(cropped_tensor)

Kích thước tensor ban đầu: (10, 10, 3)
Kích thước tensor sau khi cắt: (5, 5, 3)


In [9]:
import tensorflow as tf

# 1. Tạo ngẫu nhiên hai tensor 1-chiều x và y có 5 phần tử
# Ở đây dùng random.uniform trong khoảng [0, 10]
x = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.int32)
y = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.int32)

# 2. Sử dụng tf.where để thực hiện phép toán có điều kiện
# Cú pháp: tf.where(condition, x_if_true, y_if_false)
result = tf.where(x < y, x + y, x - y)

print("Tensor x:      ", x.numpy())
print("Tensor y:      ", y.numpy())
print("Kết quả (res): ", result.numpy())

Tensor x:       [3 4 7 1 0]
Tensor y:       [2 3 0 1 8]
Kết quả (res):  [1 1 7 0 8]


In [10]:
import tensorflow as tf

# 1. Tạo tensor x kích thước (3, 2) trong khoảng [5, 10]
x = tf.random.uniform(shape=[3, 2], minval=5, maxval=10, dtype=tf.float32)

# 2. Tạo tensor y kích thước (2, 3) trong khoảng [15, 20]
y = tf.random.uniform(shape=[2, 3], minval=15, maxval=20, dtype=tf.float32)

# 3. Lấy các giá trị đường chéo của x
# tf.linalg.diag_part sẽ trả về các phần tử x[0,0] và x[1,1]
diag_x = tf.linalg.diag_part(x)

# 4. Thực hiện phép cộng x + y
# Vì x(3,2) và y(2,3) lệch kích thước, ta cần chuyển vị y (transpose) để thành (3,2)
y_transposed = tf.transpose(y)
sum_result = x + y_transposed

print("Tensor x:\n", x.numpy())
print("\nĐường chéo của x:\n", diag_x.numpy())
print("\nTensor y (sau khi chuyển vị để cộng):\n", y_transposed.numpy())
print("\nKết quả x + y_transpose:\n", sum_result.numpy())

Tensor x:
 [[8.8206215 9.081207 ]
 [9.124594  6.709815 ]
 [5.44117   9.034732 ]]

Đường chéo của x:
 [8.8206215 6.709815 ]

Tensor y (sau khi chuyển vị để cộng):
 [[18.243639 17.412556]
 [17.059908 19.907118]
 [17.370907 16.564692]]

Kết quả x + y_transpose:
 [[27.06426  26.493763]
 [26.184502 26.616932]
 [22.812077 25.599422]]


In [11]:
import tensorflow as tf

# 1. Hàm tạo 2 tensor ngẫu nhiên kích thước (3, 2, 2)
def create_tensors():
    # Sử dụng phân phối chuẩn (Normal) cho các giá trị ngẫu nhiên
    x = tf.random.normal(shape=(3, 2, 2))
    y = tf.random.normal(shape=(3, 2, 2))
    return x, y

# 2. Định nghĩa các hàm toán học và chuyển vào Graph bằng @tf.function
@tf.function
def compute_ops(x, y):
    add_res = tf.add(x, y)
    sub_res = tf.subtract(x, y)
    mul_res = tf.multiply(x, y) # Nhân từng phần tử (Element-wise)
    div_res = tf.divide(x, y)   # Chia từng phần tử

    return add_res, sub_res, mul_res, div_res

# --- Thực thi trong Colab ---

# Bước 1: Tạo dữ liệu
tensor_x, tensor_y = create_tensors()

# Bước 2: Tính toán (Lần gọi đầu tiên sẽ "trace" hàm vào Graph)
addition, subtraction, multiplication, division = compute_ops(tensor_x, tensor_y)

# In kết quả kiểm tra
print("Tensor X:\n", tensor_x.numpy())
print("\nKết quả phép cộng (X + Y):\n", addition.numpy())

Tensor X:
 [[[ 8.0891402e-04  7.7695781e-01]
  [ 1.2303391e+00 -9.7346701e-02]]

 [[ 2.4347148e+00  1.3880382e+00]
  [ 2.6074326e+00  5.2718508e-01]]

 [[ 1.9398172e+00 -8.2551211e-01]
  [-1.1905864e+00 -4.3480691e-01]]]

Kết quả phép cộng (X + Y):
 [[[ 1.330257    0.9412257 ]
  [ 0.63866895 -0.00746845]]

 [[ 3.176158    0.706196  ]
  [ 2.782144   -1.095907  ]]

 [[ 2.458827   -1.8059752 ]
  [-2.6420743   0.5617583 ]]]


In [12]:
import tensorflow as tf

def build_sum_model(input_shape):
    # Định nghĩa 2 đầu vào riêng biệt cho x và y
    input_x = tf.keras.Input(shape=input_shape, name="input_x")
    input_y = tf.keras.Input(shape=input_shape, name="input_y")

    # Sử dụng lớp Lambda hoặc phép cộng trực tiếp để tính tổng
    # Trong TF, bạn có thể dùng layer Add để tối ưu cho model
    sum_layer = tf.keras.layers.Add()([input_x, input_y])

    # Khởi tạo model với 2 đầu vào và 1 đầu ra
    model = tf.keras.Model(inputs=[input_x, input_y], outputs=sum_layer)

    return model

# Giả sử tensor có kích thước (2, 2)
input_shape = (2, 2)
sum_model = build_sum_model(input_shape)

# Hiển thị cấu trúc model
sum_model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_x             │ (None, 2, 2)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_y             │ (None, 2, 2)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 2, 2)      │          0 │ input_x[0][0],    │
│                     │                   │            │ input_y[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
import tensorflow as tf

def build_math_model(input_shape):
    # 1. Định nghĩa các cổng đầu vào (Input layers)
    input_x = tf.keras.Input(shape=input_shape, name="input_x")
    input_y = tf.keras.Input(shape=input_shape, name="input_y")

    # 2. Thực hiện phép trừ (Hiệu)
    # Ta dùng layer Subtract
    diff = tf.keras.layers.Subtract(name="subtraction")([input_x, input_y])

    # 3. Thực hiện phép nhân (Tích - Element-wise)
    # Ta dùng layer Multiply
    prod = tf.keras.layers.Multiply(name="multiplication")([input_x, input_y])

    # 4. Khởi tạo model với 2 đầu vào và một danh sách các đầu ra
    model = tf.keras.Model(inputs=[input_x, input_y], outputs=[diff, prod])

    return model

# Giả sử kích thước tensor là (3, 2)
input_shape = (3, 2)
math_model = build_math_model(input_shape)

# Hiển thị cấu trúc mô hình
math_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_x             │ (None, 3, 2)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_y             │ (None, 3, 2)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ subtraction         │ (None, 3, 2)      │          0 │ input_x[0][0],    │
│ (Subtract)          │                   │            │ input_y[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multiplication      │ (None, 3, 2)      │          0 │ input_x[0][0],    │
│ (Multiply)          │                   │            │ input_y[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
import tensorflow as tf
import numpy as np

# ==========================================
# 1. KHỞI TẠO TENSOR (BASIC OPS)
# ==========================================
print("--- 1. Khởi tạo Tensor ---")
# Tensor [2, 3] toàn số 0
x_zeros = tf.zeros([2, 3])

# Tensor [3, 2] toàn số 5
x_fives = tf.fill([3, 2], 5)

# Tensor 1-chiều [10, 12, ..., 100]
x_range = tf.range(start=10, limit=102, delta=2)

# Tensor [3, 2] ngẫu nhiên Normal (mean=0, std=2)
x_normal = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)

# Tensor [3, 2] ngẫu nhiên Uniform [0, 2]
x_uniform = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)

print("X_range:", x_range.numpy())
print("X_normal:\n", x_normal.numpy())


# ==========================================
# 2. THAO TÁC NÂNG CAO (SHUFFLE, CROP, WHERE)
# ==========================================
print("\n--- 2. Thao tác nâng cao ---")
# Shuffle
X_to_shuffle = tf.constant([[1, 2], [3, 4], [5, 6]])
shuffled = tf.random.shuffle(X_to_shuffle)

# Random Crop (10,10,3) -> (5,5,3)
img_mock = tf.random.uniform([10, 10, 3], 0, 255, dtype=tf.int32)
cropped = tf.image.random_crop(img_mock, size=[5, 5, 3])

# Phép toán có điều kiện (Where)
a_cond = tf.random.uniform([5], 0, 10)
b_cond = tf.random.uniform([5], 0, 10)
res_cond = tf.where(a_cond < b_cond, a_cond + b_cond, a_cond - b_cond)


# ==========================================
# 3. TF.FUNCTION (GRAPH MODE)
# ==========================================
print("\n--- 3. Graph Mode với @tf.function ---")

@tf.function
def math_ops_graph(x, y):
    return tf.add(x, y), tf.subtract(x, y), tf.multiply(x, y), tf.divide(x, y)

x_graph, y_graph = tf.random.normal((3, 2, 2)), tf.random.normal((3, 2, 2))
add_g, sub_g, mul_g, div_g = math_ops_graph(x_graph, y_graph)
print("Đã thực thi phép toán trong Graph Mode.")


# ==========================================
# 4. XÂY DỰNG MODEL (KERAS FUNCTIONAL API)
# ==========================================
print("\n--- 4. Xây dựng Keras Models ---")

# A. Model tính Hiệu và Tích (Đa đầu ra)
def build_math_model(shape):
    in_x = tf.keras.Input(shape=shape, name="x")
    in_y = tf.keras.Input(shape=shape, name="y")
    diff = tf.keras.layers.Subtract(name="sub")([in_x, in_y])
    prod = tf.keras.layers.Multiply(name="mul")([in_x, in_y])
    return tf.keras.Model(inputs=[in_x, in_y], outputs=[diff, prod])

# B. Model tính Chu vi P = (a + b) * 2
def build_perimeter_model():
    length = tf.keras.Input(shape=(1,), name="length")
    width = tf.keras.Input(shape=(1,), name="width")
    sum_ab = tf.keras.layers.Add()([length, width])
    perimeter = tf.keras.layers.Lambda(lambda x: x * 2, name="calc_p")(sum_ab)
    return tf.keras.Model(inputs=[length, width], outputs=perimeter)

# Chạy thử model Chu vi
p_model = build_perimeter_model()
val_a = tf.constant([[10.0]])
val_b = tf.constant([[5.0]])
p_result = p_model.predict({'length': val_a, 'width': val_b})

print(f"Chu vi hình chữ nhật (10, 5) là: {p_result[0][0]}")

# Xuất cấu trúc model chu vi để kiểm tra
p_model.summary()

--- 1. Khởi tạo Tensor ---
X_range: [ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]
X_normal:
 [[-3.0300426 -2.9325795]
 [ 3.1493192  2.574517 ]
 [ 1.2061864  0.3863375]]

--- 2. Thao tác nâng cao ---

--- 3. Graph Mode với @tf.function ---
Đã thực thi phép toán trong Graph Mode.

--- 4. Xây dựng Keras Models ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Chu vi hình chữ nhật (10, 5) là: 30.0


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ length (InputLayer) │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ width (InputLayer)  │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 1)         │          0 │ length[0][0],     │
│                     │                   │            │ width[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ calc_p (Lambda)     │ (None, 1)         │          0 │ add_1[0][0]       │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
import tensorflow as tf

def build_total_area_model():
    # 1. Khai báo các đầu vào (Input layers)
    a = tf.keras.Input(shape=(1,), name="length")  # Chiều dài
    b = tf.keras.Input(shape=(1,), name="width")   # Chiều rộng
    c = tf.keras.Input(shape=(1,), name="height")  # Chiều cao

    # 2. Tính Diện tích xung quanh: S_xq = (a + b) * c * 2
    sum_ab = tf.keras.layers.Add(name="a_plus_b")([a, b])
    # Dùng Lambda để nhân với c và nhân với 2
    s_xq = tf.keras.layers.Lambda(lambda x: x[0] * x[1] * 2, name="S_xung_quanh")([sum_ab, c])

    # 3. Tính Diện tích 2 mặt đáy: S_day = (a * b) * 2
    s_day = tf.keras.layers.Lambda(lambda x: x[0] * x[1] * 2, name="S_2_day")([a, b])

    # 4. Tính Diện tích toàn phần: S_tp = S_day + S_xq
    s_tp = tf.keras.layers.Add(name="S_toan_phan")([s_day, s_xq])

    # 5. Khởi tạo Model
    model = tf.keras.Model(inputs=[a, b, c], outputs=s_tp)
    return model

# Khởi tạo mô hình
area_model = build_total_area_model()

# --- CHẠY THỬ NGHIỆM ---
# Giả sử a=5, b=3, c=4
# S_xq = (5+3)*4*2 = 64
# S_tp = (5*3)*2 + 64 = 30 + 64 = 94
test_a = tf.constant([[5.0]])
test_b = tf.constant([[3.0]])
test_c = tf.constant([[4.0]])

result = area_model.predict({'length': test_a, 'width': test_b, 'height': test_c})

print(f"--- KẾT QUẢ ---")
print(f"Chiều dài: 5, Chiều rộng: 3, Chiều cao: 4")
print(f"Diện tích toàn phần tính từ Model: {result[0][0]}")

# Hiển thị cấu trúc mô hình
area_model.summary()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
--- KẾT QUẢ ---
Chiều dài: 5, Chiều rộng: 3, Chiều cao: 4
Diện tích toàn phần tính từ Model: 94.0


Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ length (InputLayer) │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ width (InputLayer)  │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ a_plus_b (Add)      │ (None, 1)         │          0 │ length[0][0],     │
│                     │                   │            │ width[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ height (InputLayer) │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ S_2_day (Lambda)    │ (None, 1)         │          0 │ length[0][0],     │
│                     │                   │            │ width[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ S_xung_quanh        │ (None, 1)         │          0 │ a_plus_b[0][0],   │
│ (Lambda)            │                   │            │ height[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ S_toan_phan (Add)   │ (None, 1)         │          0 │ S_2_day[0][0],    │
│                     │                   │            │ S_xung_quanh[0][… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
import tensorflow as tf

def build_trapezoid_model():
    # 1. Khai báo 4 đầu vào là độ dài các cạnh
    ad = tf.keras.Input(shape=(1,), name="AD")
    bc = tf.keras.Input(shape=(1,), name="BC")
    ab = tf.keras.Input(shape=(1,), name="AB")
    cd = tf.keras.Input(shape=(1,), name="CD")

    # 2. Kiểm tra điều kiện 1: AD == BC
    # Cần ép kiểu hoặc chỉ định dtype cho Lambda khi làm việc với logic
    cond1 = tf.keras.layers.Lambda(lambda x: tf.equal(x[0], x[1]),
                                   name="check_AD_BC", dtype='bool')([ad, bc])

    # 3. Kiểm tra điều kiện 2: AB == CD
    cond2 = tf.keras.layers.Lambda(lambda x: tf.equal(x[0], x[1]),
                                   name="check_AB_CD", dtype='bool')([ab, cd])

    # 4. Kết hợp cả hai điều kiện (Logical AND)
    is_parallel = tf.keras.layers.Lambda(lambda x: tf.logical_and(x[0], x[1]),
                                         name="AD_parallel_BC", dtype='bool')([cond1, cond2])

    # 5. Khởi tạo Model
    model = tf.keras.Model(inputs=[ad, bc, ab, cd], outputs=is_parallel)
    return model

# Khởi tạo mô hình
model = build_trapezoid_model()

# --- KIỂM TRA THỬ NGHIỆM ---
test_data = {
    "AD": tf.constant([[5.0]]),
    "BC": tf.constant([[5.0]]),
    "AB": tf.constant([[3.0]]),
    "CD": tf.constant([[3.0]])
}

result = model.predict(test_data)
print(f"Kết quả kiểm tra (Song song?): {result[0][0]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Kết quả kiểm tra (Song song?): True


In [20]:
import tensorflow as tf

def build_base_equal_model():
    # 1. Định nghĩa các đầu vào
    # ad, bc: Độ dài hai cạnh bên
    # is_parallel: Một tensor kiểu Boolean (True/False) đại diện cho điều kiện AD // BC
    ad = tf.keras.Input(shape=(1,), name="AD_length")
    bc = tf.keras.Input(shape=(1,), name="BC_length")
    is_parallel = tf.keras.Input(shape=(1,), dtype=tf.bool, name="AD_parallel_BC")

    # 2. Kiểm tra điều kiện độ dài: AD == BC
    # Thêm dtype='bool' để Keras xử lý được kết quả logic
    equal_length = tf.keras.layers.Lambda(
        lambda x: tf.equal(x[0], x[1]), name="check_length", dtype='bool'
    )([ad, bc])

    # 3. Kết hợp hai điều kiện bằng phép AND logic
    # AB = CD <=> (AD == BC) AND (AD // BC)
    proof = tf.keras.layers.Lambda(
        lambda x: tf.logical_and(x[0], x[1]), name="proof_AB_equal_CD", dtype='bool'
    )([equal_length, is_parallel])

    # 4. Khởi tạo Model
    model = tf.keras.Model(inputs=[ad, bc, is_parallel], outputs=proof)
    return model

# Khởi tạo mô hình
model_proof = build_base_equal_model()

# --- KIỂM TRA THỬ NGHIỆM ---
# Giả sử AD = 5, BC = 5 và đã biết AD // BC (True)
test_input = {
    "AD_length": tf.constant([[5.0]]),
    "BC_length": tf.constant([[5.0]]),
    "AD_parallel_BC": tf.constant([[True]])
}

result = model_proof.predict(test_input)
print(f"Kết quả chứng minh (AB = CD?): {result[0][0]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Kết quả chứng minh (AB = CD?): True


In [22]:
import tensorflow as tf

def build_midpoint_proof_model():
    # 1. Định nghĩa các đầu vào theo mô tả
    am = tf.keras.Input(shape=(1,), name="AM")
    mb = tf.keras.Input(shape=(1,), name="MB")
    mn_parallel_bc = tf.keras.Input(shape=(1,), dtype=tf.bool, name="MN_parallel_BC")

    # 2. Kiểm tra điều kiện 1: M có là trung điểm của AB không? (AM == MB)
    # Thêm dtype='bool' để Keras xử lý được kết quả logic
    is_m_midpoint = tf.keras.layers.Lambda(
        lambda x: tf.equal(x[0], x[1]), name="check_M_midpoint", dtype='bool'
    )([am, mb])

    # 3. Kết hợp điều kiện M là trung điểm VÀ MN // BC
    # Theo định lý: Nếu một đường thẳng đi qua trung điểm một cạnh của tam giác
    # và song song với cạnh thứ hai thì nó đi qua trung điểm cạnh thứ ba.
    proof_result = tf.keras.layers.Lambda(
        lambda x: tf.logical_and(x[0], x[1]), name="proof_NA_equal_NC", dtype='bool'
    )([is_m_midpoint, mn_parallel_bc])

    # 4. Khởi tạo Model
    model = tf.keras.Model(inputs=[am, mb, mn_parallel_bc], outputs=proof_result)
    return model

# Khởi tạo mô hình
model_triangle = build_midpoint_proof_model()

# --- CHẠY THỬ NGHIỆM TRÊN COLAB ---
# Giả sử AM = 4, MB = 4 (M là trung điểm) và MN // BC là đúng (True)
test_inputs = {
    "AM": tf.constant([[4.0]]),
    "MB": tf.constant([[4.0]]),
    "MN_parallel_BC": tf.constant([[True]])
}

result = model_triangle.predict(test_inputs)

print(f"--- KẾT QUẢ CHỨNG MINH ---")
print(f"Kết luận NA = NC là: {result[0][0]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
--- KẾT QUẢ CHỨNG MINH ---
Kết luận NA = NC là: True
